
CREATE TABLE [land].[train45] (
    [cancelled]                                VARCHAR (50) NULL,
    [commuterLineID]                           VARCHAR (50) NULL,
    [departureDate]                            VARCHAR (50) NULL,
    [operatorShortCode]                        VARCHAR (50) NULL,
    [operatorUICCode]                          VARCHAR (50) NULL,
    [runningCurrently]                         VARCHAR (50) NULL,
    [timeTableRowActualTime]                   VARCHAR (50) NULL,
    [timeTableRowCancelled]                    VARCHAR (50) NULL,
    [timeTableRowCausesCategoryCode]           VARCHAR (50) NULL,
    [timeTableRowCausesCategoryCodeId]         VARCHAR (50) NULL,
    [timeTableRowCausesDetailedCategoryCode]   VARCHAR (50) NULL,
    [timeTableRowCausesDetailedCategoryCodeId] VARCHAR (50) NULL,
    [timeTableRowCausesThirdCategoryCode]      VARCHAR (50) NULL,
    [timeTableRowCausesThirdCategoryCodeId]    VARCHAR (50) NULL,
    [timeTableRowCommercialStop]               VARCHAR (50) NULL,
    [timeTableRowCommercialTrack]              VARCHAR (50) NULL,
    [timeTableRowCountryCode]                  VARCHAR (50) NULL,
    [timeTableRowDifferenceInMinutes]          VARCHAR (50) NULL,
    [timeTableRowEstimateSource]               VARCHAR (50) NULL,
    [timeTableRowLiveEstimateTime]             VARCHAR (50) NULL,
    [timeTableRowScheduledTime]                VARCHAR (50) NULL,
    [timeTableRowStationShortCode]             VARCHAR (50) NULL,
    [timeTableRowStationUICCode]               VARCHAR (50) NULL,
    [timeTableRowTrainReadyAccepted]           VARCHAR (50) NULL,
    [timeTableRowTrainReadySource]             VARCHAR (50) NULL,
    [timeTableRowTrainReadyTimestamp]          VARCHAR (50) NULL,
    [timeTableRowTrainStopping]                VARCHAR (50) NULL,
    [timeTableRowType]                         VARCHAR (50) NULL,
    [timetableAcceptanceDate]                  VARCHAR (50) NULL,
    [timetableType]                            VARCHAR (50) NULL,
    [trainCategory]                            VARCHAR (50) NULL,
    [trainNumber]                              VARCHAR (50) NULL,
    [trainType]                                VARCHAR (50) NULL,
    [version]                                  VARCHAR (50) NULL
);


